[package]
name = "rust_rts"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3"
egui-macroquad = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
gltf = "1.0"
quad-3d = { version = "0.1", package = "quad-3d" }

# Database and caching
redis = "0.24"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
mongodb = "2.8"

# Networking and compression
quic = "0.10"
lz4_flex = "0.10"
zstd = "0.13"
bincode = "1.3"

# Async and concurrency
rayon = "1.8"
crossbeam = "0.8"
parking_lot = "0.12"

# Spatial indexing
kiddo = "2.0"  # For k-d trees
rstar = "0.11" # For R-trees

# Cryptography and security
ring = "0.17"
rustls = "0.22"

# Metrics and monitoring
prometheus = "0.13"
tracing = "0.1"
tracing-subscriber = "0.3"

# Memory optimization
mimalloc = { version = "0.1", default-features = false }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
debug = true
