[package]
name = "galaxy_rts"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
glam = "0.27"
gltf = "1.4"

[[bin]]
name = "galaxy_rts"
path = "src/main.rs"
